### ISSUE TITLE
Build failure with GHC < 8.4

### ISSUE THREAD

**Issue by sjakobi** [snoyberg/monad-logger#36]
```
Control/Monad/Logger.hs:437:42: error:
    Not in scope: type constructor or class ‘Semigroup’
    |
437 | instance (Applicative m, Semigroup a) => Semigroup (NoLoggingT m a) where
    |                                          ^^^^^^^^^

Control/Monad/Logger.hs:563:42: error:
    Not in scope: type constructor or class ‘Semigroup’
    |
563 | instance (Applicative m, Semigroup a) => Semigroup (WriterLoggingT m a) where
    |                                          ^^^^^^^^^

Control/Monad/Logger.hs:680:42: error:
    Not in scope: type constructor or class ‘Semigroup’
    |
680 | instance (Applicative m, Semigroup a) => Semigroup (LoggingT m a) where
    |                                          ^^^^^^^^^
```

This issue was introduced by https://github.com/snoyberg/monad-logger/pull/34 (CC @jship).

As a Hackage trustee, I have revised the affected version 0.3.37: https://hackage.haskell.org/package/monad-logger-0.3.37/revisions/
